name: Tests on k3s

on:
  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish image (true|false)'
        required: true
        default: 'false'
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PUBLISH: ${{ github.event.inputs.publish }}
      DOCKER_BUILDKIT: 1
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v2
    - name: Prepare docker registry and k3s
      run: |
        ./create-cluster-k3s.sh
        while [[ $(kubectl get nodes -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}') != "True" ]]; do echo "Waiting for cluster nodes to be ready"; sleep 2; done
    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3
    - name: Build image
      run: |
        export VERSION=$(cat app/package.json| jq -r '.version')
        docker build -f Dockerfile -t registry.localhost:5000/pbochynski/hello-k3s:$VERSION app
        docker push registry.localhost:5000/pbochynski/hello-k3s:$VERSION
    - name: Run tests
      run: |
        cd app
        npm install
        npx mocha integration-test
    - name: Publish image
      run: |
        export VERSION=$(cat app/package.json| jq -r '.version')
        if [[ "$PUBLISH" == "true" ]]; then
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          docker tag registry.localhost:5000/pbochynski/hello-k3s:$VERSION ghcr.io/pbochynski/hello-k3s:$VERSION
          docker push ghcr.io/pbochynski/hello-k3s:$VERSION
        fi
